apiVersion: v2
name: my-chart
description: A Garden Helm Chart using Helmet library to deploy
type: application
version: "0.1.0"
maintainers:
  - name: {{ cookiecutter.full_name }}
    email: {{ cookiecutter.email }}

dependencies:
  - name: helmet
    version: 0.7.0
    repository: https://companyinfo.github.io/helm-charts
    import-values: # <== It is mandatory if you want to import the Helmet default values.
      - defaults