apiVersion: garden.io/v1
kind: Project
name: go-seed
defaultEnvironment: local
dotIgnoreFile: .gitignore

variables:
  # Replace underscores as Kubernetes namespaces do not allow them.
  user-namespace: go-seed-${kebabCase(local.username)} # make sure to explain all of this.
  registryHostname: docker.io # Replace with your own registry in case it's needed.
  registryNamespace: shankyweb # Replace this with your Dockerhub/Registry username.

environments:

  - name: local
    defaultNamespace: ${var.user-namespace}
    variables:
      base-hostname: local.demo.garden
      targetStage: development

  - name: production
    defaultNamespace: ${var.user-namespace}
    variables:
      base-hostname: {{cookiecutter.domain_name}}
      targetStage: production

providers:
  - name: local-kubernetes
    environments: [local]
    namespace: ${environment.namespace}
    defaultHostname: ${var.base-hostname}
    context: docker-desktop

  # Deploy to remote production environment using the same configuration as local.
  - name: kubernetes
    environments: [production]
    context: admin@main-ce
    setupIngressController: nginx
    buildMode: local-docker
    imagePullSecrets:
      - name: regcred
        namespace: default
    deploymentRegistry:
      hostname: ${variables.registryHostname}
      namespace: ${variables.registryNamespace}
    namespace: ${environment.namespace}
    defaultHostname: ${var.base-hostname}
